dist: xenial
language: python
python:
- '3.7'
install:
    - python -m pip install dlint
deploy:
  provider: pypi
  user: inbalboa
  password:
    secure: "HjSNx45wYwcA6WvNKqMEKYfEAqCmKSAZqyPOJPbo2C2Olg5vwZfhCyBXTp9pqyODk5kldQt6eoD1pMfLEJj9r/50cpz7WXUhby6zXHBZmwAgS9zNqWqnK4ntE5vg4Z/5fZS3gzGGXG2eSbF9TAYqclRhwkQOJVW7Zg472K85KW867BFJX11+nXQUmQ9IktiPUdKFIvZinfOGkV1cTQFfTVGNn+7SGm0T1os2mT5634NQC2bq8pEQL5i+V9vEe9sFvOVPN8Bw5tDAsR5vs0muONofvrU9XEXUJBjU6akScpA1dV1I+0xKDqxdEaLptL76aPTNRA/ZeL0Qi0aG7UtT5l8WfbLY5E8M+9FsrEXITowPKOcBcAINCAYZ770wKDsQk73husmJ7p2wXHtUYpAA35keaoVdWEvjH3YsrXB/OCdja1NYWrkZ4H1R0WNcuzg0gaHgzvhOp11WeUsIEMZ3Yj0Dm3Gq4lMGDwc+mFvsraTSkKBcJR1XgO4Cu1dZfolSbxD6MuBnyHr2ZHNwVvWUeF55yJVk9wcTBlcSgTW6KYobiRukBzKhS78hll8PIHmj0/Ir6iVJwNqvDWM9lnMj+IgxlBz08WMLziTKr43wfEOkct9gV7MMl+caMO6LJqntawSnDoo/Kxv4FJqhEV6r+9r9DqdErXGGabgtnWvTLXo="
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    branch: master
    tags: true
script:
    - python -m flake8 --select=DUO pymstodo
